[2025-09-16 15:13:05,902] - ERROR    - app.py       - <log_exception  > :: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Project\Study\uv-web-demo\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\Study\uv-web-demo\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\Study\uv-web-demo\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\Study\uv-web-demo\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\Study\uv-web-demo\src\uv-web-demo\route\main.py", line 21, in index
    books = DB.query("SELECT * FROM t_book")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\Study\uv-web-demo\src\uv-web-demo\db.py", line 33, in query
    cur.execute(sql, params or [])
sqlite3.OperationalError: no such table: t_book
[2025-09-16 15:13:05,905] - ERROR    - __init__.py  - <server_error   > :: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "C:\Project\Study\uv-web-demo\.venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\Study\uv-web-demo\.venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\Study\uv-web-demo\.venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\Study\uv-web-demo\.venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\Study\uv-web-demo\src\uv-web-demo\route\main.py", line 21, in index
    books = DB.query("SELECT * FROM t_book")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Project\Study\uv-web-demo\src\uv-web-demo\db.py", line 33, in query
    cur.execute(sql, params or [])
sqlite3.OperationalError: no such table: t_book
